name: CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t proyecto-devops .